---
name: awspub
summary: A tool to aid in the publication of aws images
description: |
  A tool to aid in the publication of AWS EC2 images.

  Credentials in ~/.aws/ need to be configured to be
  able to use this tool.

  Note: this snap is provided and maintained by Canonical!
  (**not** by Amazon/AWS)
version: git
base: core24
confinement: strict
license: GPL-3.0
issues: https://github.com/canonical/awspub/issues
website: https://canonical-awspub.readthedocs-hosted.com/
platforms:
  amd64:
    build-on: [amd64]
  arm64:
    build-on: [arm64]

plugs:
  dot-aws-config:
    interface: personal-files
    read:
    - $HOME/.aws/config
  dot-aws-credentials:
    interface: personal-files
    read:
    - $HOME/.aws/credentials
  dot-aws-models:
    interface: personal-files
    read:
    - $HOME/.aws/models

apps:
  awspub:
    command: bin/awspub
    environment:
      # need to set $HOME to the real HOME here because this is a strict snap
      # and the creds for aws are in $HOME/.aws
      HOME: $SNAP_REAL_HOME
    plugs:
      - home
      - network
      - dot-aws-config
      - dot-aws-credentials
      - dot-aws-models

parts:
  awspub:
    plugin: poetry
    source: .
    build-packages:
      - git
